### PR TITLE
Update translate_dynamic.txt

### PR DESCRIPTION
**Pull request by pjoakes**
change for clarity.

---

This change is [Reviewable](https://reviewable.io/reviews/door43/d43-en/230)

### CODE REVIEW

**Comment by richmahn** [comment]
@pjoakes This has conflicts. Do you still want this PR?

**Comment by pjoakes** [comment]
Yes, I would like to have those changes. I don't know what you mean by conflicts.

**Comment by richmahn** [comment]
@pjoakes There's a conflict though, apparently someone has edited the same line as you did. See the Files changed tab on this Pull Request page to see them.

**Comment by richmahn** [comment]
Not sure what changed though...doesn't look to be any.

**Comment by richmahn** [comment]
@pjoakes I just made the changes directly in this repo, closing this. https://github.com/Door43/d43-en/commit/2f75ea38114a5beef1d681cb1aab8d19b6a08208

**Pull request closed without merging**
